package com.backend.hotelreservationapi.user_module.enums;

public enum PermissionEnum {
    //USERS
    PROFILE_VIEW,
    PROFILE_UPDATE,
    APPLICATION_CREATE,
    APPLICATION_VIEW,
    APPLICATION_VIEW_ALL,

    //PROPERTY  MANAGERS
    ROOM_MANAGE,
    BOOKING_MANAGE,
    REPORT_VIEW,
    PROPERTY_POST_CREATE,
    PROPERTY_POST_UPDATE,
    PROPERTY_POST_VIEW,
    PROPERTY_POST_VIEW_ALL,
    PROPERTY_POST_DELETE,

    //ADMIN
    ADMIN_APPLICATION_VIEW_ALL,
    ADMIN_APPLICATION_VIEW_SINGLE,
    ADMIN_APPLICATION_UPDATE,




}
