spring.application.name=Hotel Reservation API

spring.jpa.hibernate.ddl-auto=update

# Email configuration
sendgrid.api.key=${API_KEY}
sendgrid.from.email=${VERIFIED_EMAIL}


spring.mail.properties.mail.debug=true

# Jwt
jwt.secret=${JWT_SECRET_KEY}
jwt.access-token-expiration=${ACCESS_TOKEN_EXPIRATION}
jwt.refresh-token-expiration=${REFRESH_TOKEN_EXPIRATION}


admin.email=${ADMIN_EMAIL}

file.upload.directory=/app/uploads
file.upload.max-size-profile-picture=2MB

cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.cloud-api-key=${CLOUD_API_KEY}
cloudinary.api-secret=${CLOUD_SECRET}

spring.devtools.restart.enabled=true