spring.application.name=Hotel Reservation API

spring.jpa.hibernate.ddl-auto=update

# Email configuration
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=${EMAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${EMAIL_STARTTLS_ENABLE}
spring.mail.properties.mail.smtp.starttls.required=${EMAIL_STARTTLS_REQUIRED}

spring.mail.properties.mail.debug=true

# Jwt
jwt.secret=${JWT_SECRET_KEY}
jwt.access-token-expiration=${ACCESS_TOKEN_EXPIRATION}
jwt.refresh-token-expiration=${REFRESH_TOKEN_EXPIRATION}


admin.email=${ADMIN_EMAIL}