spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


# Email configuration
sendgrid.api.key=test-api-key
sendgrid.from.email=test@gmail.com


# Jwt
jwt.secret=klkafljlwjljflkwjljlkjflwjljfwljlfjlwkjlfjlkjfwjlkfjwkjlkfwjlkjwkfjkjwfljlwfjljwfjlwjwkfjwjljklwkwfkjwjf
jwt.access-token-expiration=15
jwt.refresh-token-expiration=7

admin.email=tommy@gmail.com